// 42. Write a JavaScript program to check whether three given numbers are 
// increasing in strict or in soft mode.  
// Note: Strict mode -> 10, 15, 31 : Soft mode -> 24, 22, 31 or 22, 22, 31 

// 1. WHAT IS STRICT MODE ?
// => WHEN WE SAY THAT A SET OF NUMBERS IS "STRICTLY INCREASING," 
// => IT MEANS THAT EACH NUMBER IN THE SEQUENCE IS GREATER THAN THE PREVIOUS NUMBER,
// => AND NO TWO NUMBERS CAN BE EQUAL. IN OTHER WORDS, THE SEQUENCE MUST HAVE A CLEAR
// => AND CONSISTENT UPWARD TREND WITHOUT ANY PLATEAUS OR EQUAL VALUES.

// 2. WHAT IS SOFT MODE ?
// => IN SOFT MODE, A SEQUENCE IS CONSIDERED "SOFTLY INCREASING" IF EACH NUMBER IS GREATER 
// => THAN OR EQUAL TO THE PREVIOUS NUMBER. THIS MODE ALLOWS FOR EQUAL VALUES IN THE SEQUENCE,
// => SO IT'S MORE PERMISSIVE THAN STRICT MODE.